name: CI

on:
  push:
  workflow_dispatch:

jobs:
  job:
    name: Check

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json

      - name: Install dependencies
        run: npm install

      - name: Check
        run: npm run check:ci
